image: node:21-bullseye

stages:
  - build
  - deploy

.cache-build:
  cache:
    key: build-${CI_COMMIT_REF_SLUG}
    paths:
      - dist

.cache-build-pull:
  extends:
    - .cache-build
  cache:
    policy: pull

.env:dev:
  environment:
    name: dev
    url: ${ENV_URL}

.env:prod:
  environment:
    name: prod
    url: ${ENV_URL}

build:front:
  stage: build
  extends:
    - .cache-build
  script:
    - npm install
    - npm run build

.deploy:front:
  stage: deploy
  extends:
    - .cache-build-pull
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - scripts/deploy.sh
  needs: ["build:front"]

deploy:front:prod:
  extends:
    - .env:prod
    - .deploy:front
  only:
    - master

deploy:front:dev:
  extends:
    - .env:dev
    - .deploy:front
  except:
    - master
