image: node:21-bullseye

stages:
  - build
  - deploy

.cache-build:
  cache:
    key: build-${CI_COMMIT_REF_SLUG}
    paths:
      - dist

.cache-build-pull:
  extends:
    - .cache-build
  cache:
    policy: pull

build:front:prod:
  stage: build
  extends:
    - .cache-build
  script:
    - scripts/build.sh

deploy:front:prod:
  stage: deploy
  extends:
    - .cache-build-pull
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  environment:
    name: prod
  script:
    - scripts/deploy.sh
  needs: ["build:front:prod"]
  only:
    - master
