export const bonusList = [
  {
    id: 1,
    cost: 1e7,
    name: "Confinement I",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e4,
  },
  {
    id: 2,
    cost: 1e8,
    name: "Confinement II",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e5,
  },
  {
    id: 3,
    cost: 1e9,
    name: "Confinement III",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e6,
  },
  {
    id: 4,
    cost: 1e10,
    name: "Confinement IV",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e7,
  },
  {
    id: 5,
    cost: 1e11,
    name: "Confinement V",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e8,
  },
  {
    id: 6,
    cost: 1e12,
    name: "Confinement VI",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e9,
  },
  {
    id: 7,
    cost: 1e13,
    name: "Confinement VII",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e10,
  },
  {
    id: 8,
    cost: 1e14,
    name: "Confinement VIII",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e11,
  },
  {
    id: 9,
    cost: 1e15,
    name: "Confinement IX",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e12,
  },
  {
    id: 10,
    cost: 1e16,
    name: "Confinement X",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e13,
  },
  {
    id: 14,
    cost: 1e17,
    name: "Confinement XI",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e14,
  },
  {
    id: 15,
    cost: 1e18,
    name: "Confinement XII",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e15,
  },
  {
    id: 16,
    cost: 1e19,
    name: "Confinement XIII",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e16,
  },
  {
    id: 11,
    cost: 1.5e9,
    name: "Dose de rappel",
    type: bonusType.perkTimerReducer,
    value: 2,
    neededProduction: 5e5,
  },
  {
    id: 12,
    cost: 1.5e12,
    name: "Chômage partiel",
    type: bonusType.autoClickMultiplicator,
    value: 2,
    neededProduction: 5e7,
  },
  {
    id: 13,
    cost: 4.5e12,
    name: "Seconde vague",
    type: bonusType.perkEffectMultiplicator,
    value: 2,
    neededProduction: 7.5e7,
  },
  {
    id: 17,
    cost: 1.08e14,
    name: "Investissement dans les crypto-monnaies",
    type: bonusType.productionMultiplicator,
    value: 2,
    neededProduction: 5e9,
  },
  {
    id: 18,
    cost: 1.08e16,
    name: "Investissement dans les NFT",
    type: bonusType.productionMultiplicator,
    value: 2,
    neededProduction: 5e11,
  },
  {
    id: 19,
    cost: 1.08e16,
    name: "Prime à l'emploi",
    type: bonusType.buildingCountMultiplicator,
    value: 0.01,
    value2: 100,
    neededProduction: 5e8,
  },
];
