export const bonusList = [
  {
    id: 1,
    cost: 1e5,
    name: "Confinement I",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e4,
  },
  {
    id: 2,
    cost: 1e6,
    name: "Confinement II",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e5,
  },
  {
    id: 3,
    cost: 1e7,
    name: "Confinement III",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e6,
  },
  {
    id: 4,
    cost: 1e8,
    name: "Confinement IV",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e7,
  },
  {
    id: 5,
    cost: 1e9,
    name: "Confinement V",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e8,
  },
  {
    id: 6,
    cost: 1e10,
    name: "Confinement VI",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e9,
  },
  {
    id: 7,
    cost: 1e11,
    name: "Confinement VII",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e10,
  },
  {
    id: 8,
    cost: 1e12,
    name: "Confinement VIII",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e11,
  },
  {
    id: 9,
    cost: 1e13,
    name: "Confinement IX",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e12,
  },
  {
    id: 10,
    cost: 1e14,
    name: "Confinement X",
    type: bonusType.productionMultiplicator,
    value: 1.05,
    neededProduction: 1e13,
  },
  {
    id: 11,
    cost: 1.5e9,
    name: "Dose de rappel",
    type: bonusType.perkTimerReducer,
    value: 2,
    neededProduction: 5e5,
  },
];
