import { IBuilding } from "../logic/Building.logic";

export const buidlingList: IBuilding[] = [
  {
    id: 1,
    baseAmount: 25,
    amountMultiplier: 1.1,
    name: "Chercheur",
    baseProduction: 0.2,
  },
  {
    id: 2,
    baseAmount: 1.5e2,
    amountMultiplier: 1.2,
    name: "Raoult la fripouille",
    baseProduction: 1,
  },
  {
    id: 4,
    baseAmount: 1e3,
    amountMultiplier: 1.15,
    baseProduction: 5,
    name: "",
    img: {
      src: "./static/img/ouh.png",
    },
  },
  {
    id: 5,
    baseAmount: 1e4,
    amountMultiplier: 1.15,
    baseProduction: 25,
    name: "Richard sans peur",
  },
  {
    id: 6,
    baseAmount: 1e5,
    amountMultiplier: 1.15,
    baseProduction: 1e2,
    name: "Lorenzo Lovegun",
  },
  {
    id: 7,
    baseAmount: 1.2e6,
    amountMultiplier: 1.15,
    baseProduction: 1e3,
    name: "Thamos, destructeur des mondes",
  },
  {
    id: 8,
    baseAmount: 8e6,
    amountMultiplier: 1.15,
    baseProduction: 2e3,
    name: "Patoche Balkanoche",
    description: "Faîtes moi confiances les potos.",
  },
  {
    id: 9,
    baseAmount: 1.6e7,
    amountMultiplier: 1.15,
    baseProduction: 3.5e3,
    name: "Sardoche",
    description: "C'était sûr qu'il allait venir.",
  },
  {
    id: 10,
    baseAmount: 2.4e8,
    amountMultiplier: 1.15,
    baseProduction: 1e4,
    name: "Jean-Michel Cinquejet",
    description: "Quelqu'un a le code de la wifi ?",
  },
  {
    id: 11,
    baseAmount: 4e9,
    amountMultiplier: 1.15,
    baseProduction: 1e5,
    name: "Leeroy Jenkins",
    description: "Vous voulez du poulet ?",
  },
  {
    id: 12,
    baseAmount: 1.2e10,
    amountMultiplier: 1.15,
    baseProduction: 5e5,
    name: "Canard man",
    description: "Les bugs n'ont qu'à bien se tenir.",
  },
  {
    id: 13,
    baseAmount: 2.8e11,
    amountMultiplier: 1.1,
    baseProduction: 1.5e6,
    name: "Jeanne d'Haussecourt",
    description: "On m'a appelée ?",
  },
  {
    id: 3,
    baseAmount: 5e12,
    amountMultiplier: 1.2,
    name: "Le Christ Cosmique",
    baseProduction: 5e6,
  },
  {
    id: 14,
    baseAmount: 2e13,
    amountMultiplier: 1.1,
    baseProduction: 1.5e7,
    name: "Maître Miyagi",
  },
  {
    id: 15,
    baseAmount: 1e15,
    amountMultiplier: 1.1,
    baseProduction: 9e7,
    name: "Robert the Bruce",
  },
  {
    id: 16,
    baseAmount: 5e16,
    amountMultiplier: 1.1,
    baseProduction: 9e8,
    name: "ID 16",
  },
  {
    id: 17,
    baseAmount: 1e18,
    amountMultiplier: 1.1,
    baseProduction: 1.5e10,
    name: "ID 17",
  },
  {
    id: 18,
    baseAmount: 1.5e20,
    amountMultiplier: 1.1,
    baseProduction: 9e10,
    name: "ID 18",
  },
];
export default {
  buidlingList,
};
