import { IBuilding } from "../logic/Building.logic";

export const buidlingList: IBuilding[] = [
  {
    id: 1,
    amountMultiplier: 1.1,
    baseAmount: 25,
    baseProduction: 0.2,
    name: "Chercheur",
  },
  {
    id: 2,
    amountMultiplier: 1.2,
    baseAmount: 1.5e2,
    baseProduction: 1,
    name: "Raoult la fripouille",
    neededProduction: 1,
  },
  {
    id: 4,
    amountMultiplier: 1.15,
    baseAmount: 1e3,
    baseProduction: 5,
    img: {
      src: "./static/img/ouh.png",
    },
    name: "",
    neededProduction: 10,
  },
  {
    id: 5,
    amountMultiplier: 1.15,
    baseAmount: 1e4,
    baseProduction: 25,
    name: "Richard sans peur",
    neededProduction: 50,
  },
  {
    id: 6,
    amountMultiplier: 1.15,
    baseAmount: 1e5,
    baseProduction: 1e2,
    name: "Lorenzo Lovegun",
    neededProduction: 300,
  },
  {
    id: 7,
    amountMultiplier: 1.15,
    baseAmount: 1.2e6,
    baseProduction: 1e3,
    name: "Thamos, destructeur des mondes",
    neededProduction: 1000,
  },
  {
    id: 8,
    amountMultiplier: 1.15,
    baseAmount: 8e6,
    baseProduction: 2e3,
    description: "Faîtes moi confiances les potos.",
    name: "Patoche Balkanoche",
    neededProduction: 3000,
  },
  {
    id: 9,
    amountMultiplier: 1.15,
    baseAmount: 1.6e7,
    baseProduction: 3.5e3,
    description: "C'était sûr qu'il allait venir.",
    name: "Sardoche",
    neededProduction: 10000,
  },
  {
    id: 10,
    amountMultiplier: 1.15,
    baseAmount: 2.4e8,
    baseProduction: 1e4,
    description: "Quelqu'un a le code de la wifi ?",
    name: "Jean-Michel Cinquejet",
    neededProduction: 25000,
  },
  {
    id: 11,
    amountMultiplier: 1.15,
    baseAmount: 4e9,
    baseProduction: 1e5,
    description: "Vous voulez du poulet ?",
    name: "Leeroy Jenkins",
    neededProduction: 50000,
  },
  {
    id: 12,
    amountMultiplier: 1.15,
    baseAmount: 1.2e10,
    baseProduction: 5e5,
    description: "Les bugs n'ont qu'à bien se tenir.",
    name: "Canard man",
    neededProduction: 100000,
  },
  {
    id: 13,
    amountMultiplier: 1.1,
    baseAmount: 2.8e11,
    baseProduction: 1.5e6,
    description: "On m'a appelée ?",
    name: "Jeanne d'Haussecourt",
    neededProduction: 10000,
  },
  {
    id: 3,
    amountMultiplier: 1.2,
    baseAmount: 5e12,
    baseProduction: 5e6,
    name: "Le Christ Cosmique",
    neededProduction: 50000,
  },
  {
    id: 14,
    amountMultiplier: 1.1,
    baseAmount: 2e13,
    baseProduction: 1.5e7,
    name: "Maître Miyagi",
    neededProduction: 200000,
  },
  {
    id: 15,
    amountMultiplier: 1.1,
    baseAmount: 1e15,
    baseProduction: 9e7,
    name: "Robert the Bruce",
    neededProduction: 600000,
  },
  {
    id: 16,
    amountMultiplier: 1.1,
    baseAmount: 5e16,
    baseProduction: 9e8,
    name: "ID 16",
    neededProduction: 2000000,
  },
  {
    id: 17,
    amountMultiplier: 1.1,
    baseAmount: 1e18,
    baseProduction: 1.5e10,
    name: "ID 17",
    neededProduction: 5000000,
  },
  {
    id: 18,
    amountMultiplier: 1.1,
    baseAmount: 1.5e20,
    baseProduction: 9e10,
    name: "ID 18",
    neededProduction: 10000000,
  },
];
export default {
  buidlingList,
};
