export const upgradeList: IBuildingUpgrade[] = [
  {
    id: 10,
    buildingId: buildingType.chercheur,
    cost: 5e2,
    multiplicator: 2,
    name: "Casio Pro",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 11,
    buildingId: buildingType.chercheur,
    cost: 5e3,
    multiplicator: 2,
    name: "Casio Plus",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 12,
    buildingId: buildingType.chercheur,
    cost: 2e4,
    multiplicator: 2,
    name: "Casio Pro Plus",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 13,
    buildingId: buildingType.chercheur,
    cost: 5e4,
    multiplicator: 4,
    name: "Casio X Texas",
    description: "",
    requestedLevel: 50,
  },
  {
    id: 20,
    buildingId: buildingType.raoult,
    cost: 10000,
    multiplicator: 2,
    name: "La chloroquine pour les nuls",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 21,
    buildingId: buildingType.raoult,
    cost: 30000,
    multiplicator: 2,
    name: "Cloroquina para tontos",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 22,
    buildingId: buildingType.raoult,
    cost: 60000,
    multiplicator: 2,
    name: "Хлорохин для чайников",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 40,
    buildingId: buildingType.monkey,
    cost: 50000,
    multiplicator: 2,
    name: "Ouh.",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 41,
    buildingId: buildingType.monkey,
    cost: 1e6,
    multiplicator: 2,
    name: "Ouh. Ouh.",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 42,
    buildingId: buildingType.monkey,
    cost: 2e6,
    multiplicator: 2,
    name: "Ouh. Ouh. Ouh.",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 50,
    buildingId: buildingType.richard,
    cost: 1e6,
    multiplicator: 2,
    name: "Kit de survie pour scout",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 51,
    buildingId: buildingType.richard,
    cost: 4e6,
    multiplicator: 2,
    name: "Cape en nylon",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 52,
    buildingId: buildingType.richard,
    cost: 1.2e7,
    multiplicator: 2,
    name: "Richardmobile",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 60,
    buildingId: buildingType.lorenzo,
    cost: 9e6,
    multiplicator: 2,
    name: "Séance de dédicace",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 61,
    buildingId: buildingType.lorenzo,
    cost: 1.5e7,
    multiplicator: 2,
    name: "Compilation DVD",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 62,
    buildingId: buildingType.lorenzo,
    cost: 5e7,
    multiplicator: 2,
    name: "Ouverture d'un compte JustFans",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 70,
    buildingId: buildingType.thamos,
    cost: 3e7,
    multiplicator: 2,
    name: "Paire de mouffles",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 71,
    buildingId: buildingType.thamos,
    cost: 1.2e8,
    multiplicator: 2,
    name: "Fermette à rénover",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 72,
    buildingId: buildingType.thamos,
    cost: 6e8,
    multiplicator: 2,
    name: "👌",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 80,
    buildingId: buildingType.patoche,
    cost: 1.3e8,
    multiplicator: 2,
    name: "Optimisation fiscale",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 81,
    buildingId: buildingType.patoche,
    cost: 5e8,
    multiplicator: 2,
    name: "Erreur de la banque en votre faveur",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 82,
    buildingId: buildingType.patoche,
    cost: 1e9,
    multiplicator: 2,
    name: "Exempté d'impôt",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 90,
    buildingId: buildingType.sardoche,
    cost: 7e8,
    multiplicator: 2,
    name: "Abdul",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 91,
    buildingId: buildingType.sardoche,
    cost: 1.2e9,
    multiplicator: 2,
    name: "Coquelicot",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 92,
    buildingId: buildingType.sardoche,
    cost: 6e9,
    multiplicator: 2,
    name: "Abricot",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 100,
    buildingId: buildingType.jeanMichel,
    cost: 4e9,
    multiplicator: 2,
    name: "Forfait illimité",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 101,
    buildingId: buildingType.jeanMichel,
    cost: 1.2e10,
    multiplicator: 2,
    name: "Client premium à vie",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 102,
    buildingId: buildingType.jeanMichel,
    cost: 6e10,
    multiplicator: 3,
    name: "Nano-puce sous-cutanée",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 110,
    buildingId: buildingType.leeroy,
    cost: 3e10,
    multiplicator: 2,
    name: "LEEEEEEEEEEEEEEEEEEEE",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 111,
    buildingId: buildingType.leeroy,
    cost: 9e10,
    multiplicator: 2,
    name: "ROOOOOOOOOOOOY",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 112,
    buildingId: buildingType.leeroy,
    cost: 3.2e11,
    multiplicator: 3,
    name: "JEEEEEEEENNKINS",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 113,
    buildingId: buildingType.leeroy,
    cost: 1.6e12,
    multiplicator: 4,
    name: "Copains pour la vie",
    description: "",
    requestedLevel: 50,
  },
  {
    id: 120,
    buildingId: buildingType.canardMan,
    cost: 1.5e11,
    multiplicator: 2,
    name: "Lampe à UV du commisaire Magret",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 121,
    buildingId: buildingType.canardMan,
    cost: 4.5e11,
    multiplicator: 3,
    name: "Ceinture de grenades canards",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 122,
    buildingId: buildingType.canardMan,
    cost: 1.6e12,
    multiplicator: 2,
    name: "Gant du conquérant",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 123,
    buildingId: buildingType.canardMan,
    cost: 8e12,
    multiplicator: 4,
    name: "Alliance avec l'Aigle de la Nuit",
    description: "Le début de la ligue des oiseaux masqués.",
    requestedLevel: 50,
  },
  {
    id: 130,
    buildingId: buildingType.jeanne,
    cost: 6e11,
    multiplicator: 2,
    name: "Paquet de galettes Saint-Michel",
    description: "Pur beurre.",
    requestedLevel: 10,
  },
  {
    id: 131,
    buildingId: buildingType.jeanne,
    cost: 1.8e12,
    multiplicator: 2,
    name: "xXx D4RK J34NN3 xXx",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 132,
    buildingId: buildingType.jeanne,
    cost: 5e12,
    multiplicator: 3,
    name: "Manteau ignifugé",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 133,
    buildingId: buildingType.jeanne,
    cost: 2.5e13,
    multiplicator: 4,
    name: "Message divin",
    description: "",
    requestedLevel: 50,
  },
  {
    id: 190,
    buildingId: buildingType.katlyn,
    cost: 2e12,
    multiplicator: 2,
    name: "Morgan, la poupée vaudou",
    description: `Elle fait "waouh" quand on appuie dessus.`,
    requestedLevel: 10,
  },
  {
    id: 191,
    buildingId: buildingType.katlyn,
    cost: 5e12,
    multiplicator: 2,
    name: "Kazoo en adamantium",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 192,
    buildingId: buildingType.katlyn,
    cost: 1e13,
    multiplicator: 3,
    name: "Grimoire d'invocation démoniaque",
    description:
      "Permet d'invoquer des démons tels que Chase, Stella ou Marcus.",
    requestedLevel: 30,
  },
  {
    id: 193,
    buildingId: buildingType.katlyn,
    cost: 5e13,
    multiplicator: 4,
    name: "Portail vers les Enfers.",
    description: "Un accès direct aux mondes démoniaques.",
    requestedLevel: 50,
  },
  {
    id: 30,
    buildingId: buildingType.christ,
    cost: 2.5e12,
    multiplicator: 2,
    name: "Bâton de Merlin",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 31,
    buildingId: buildingType.christ,
    cost: 7.5e12,
    multiplicator: 2,
    name: "Couronne de joyaux",
    description: "Digne d'un grand monarque.",
    requestedLevel: 20,
  },
  {
    id: 32,
    buildingId: buildingType.christ,
    cost: 2e13,
    multiplicator: 3,
    name: "Prophétie de Sylvanus Oriana",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 33,
    buildingId: buildingType.christ,
    cost: 1.2e14,
    multiplicator: 4,
    name: "Légende de l'Homme vert",
    description: "",
    requestedLevel: 50,
  },
  {
    id: 140,
    buildingId: buildingType.miyagi,
    cost: 1e13,
    multiplicator: 2,
    name: "Keikogi en soie d'exception",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 141,
    buildingId: buildingType.miyagi,
    cost: 3e13,
    multiplicator: 2,
    name: "Mode d'emploi du Gōjū-ryū",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 142,
    buildingId: buildingType.miyagi,
    cost: 9e13,
    multiplicator: 3,
    name: `"Sensei 8": Autobiographie`,
    description: "",
    requestedLevel: 30,
  },
  {
    id: 143,
    buildingId: buildingType.miyagi,
    cost: 4.5e14,
    multiplicator: 4,
    name: `Nunchaku laser`,
    description:
      "Mi nunchaku, mi sabre-laser. Et en plus il brille dans la nuit.",
    requestedLevel: 50,
  },
  {
    id: 200,
    buildingId: buildingType.bebou,
    cost: 6e14,
    multiplicator: 2,
    name: "Cérémonie du gnogni",
    description: "",
    requestedLevel: 10,
  },
  {
    id: 201,
    buildingId: buildingType.bebou,
    cost: 1.8e15,
    multiplicator: 2,
    name: "Offrande au dieu Gnok",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 202,
    buildingId: buildingType.bebou,
    cost: 4e15,
    multiplicator: 3,
    name: "Pacte commercial avec l'empire du Cringe",
    description: "",
    requestedLevel: 30,
  },
  {
    id: 203,
    buildingId: buildingType.bebou,
    cost: 1e16,
    multiplicator: 4,
    name: "Apparition de Gnok sur Terre.",
    description: "",
    requestedLevel: 50,
  },
  {
    id: 150,
    buildingId: buildingType.bruce,
    cost: 4e15,
    multiplicator: 2,
    name: "Larme saline",
    description: "Un immense topaze, joyau de la famille Lomsaley.",
    requestedLevel: 10,
  },
  {
    id: 151,
    buildingId: buildingType.bruce,
    cost: 1.2e16,
    multiplicator: 2,
    name: "Certificat de propriété d'une mine de sel",
    description: "",
    requestedLevel: 20,
  },
  {
    id: 152,
    buildingId: buildingType.bruce,
    cost: 3.6e16,
    multiplicator: 3,
    name: `Triggered`,
    description: "Aren't you Bruce ?",
    requestedLevel: 30,
  },
  {
    id: 153,
    buildingId: buildingType.bruce,
    cost: 1e17,
    multiplicator: 4,
    name: `Super-triggered`,
    description: "Qui peut le stopper ?",
    requestedLevel: 50,
  },
  {
    id: 160,
    buildingId: buildingType.petyr,
    cost: 4e17,
    multiplicator: 2,
    name: `Guide du reporter de l'extrême`,
    description: "",
    requestedLevel: 10,
  },
  {
    id: 161,
    buildingId: buildingType.petyr,
    cost: 1.2e18,
    multiplicator: 2,
    name: `Infiltration d'un gang de la West Coast`,
    description: `Le reportage rêvé après 6 mois dans les rues du Bosquet.`,
    requestedLevel: 20,
  },
  {
    id: 162,
    buildingId: buildingType.petyr,
    cost: 3.6e18,
    multiplicator: 3,
    name: `Théorie du complot des pangolins`,
    description: "On nous cache tout.",
    requestedLevel: 30,
  },
  {
    id: 163,
    buildingId: buildingType.petyr,
    cost: 1.2e19,
    multiplicator: 4,
    name: `Prix Pulitzer`,
    description: "",
    requestedLevel: 50,
  },
];

export const buildingList: IBuilding[] = [
  {
    id: buildingType.chercheur,
    amountMultiplier: 1.05,
    baseAmount: 25,
    baseProduction: 0.2,
    name: "Chercheur",
  },
  {
    id: buildingType.raoult,
    amountMultiplier: 1.1,
    baseAmount: 1.5e2,
    baseProduction: 1,
    name: "Raoult la fripouille",
    neededProduction: 1,
  },
  {
    id: buildingType.monkey,
    amountMultiplier: 1.05,
    baseAmount: 1e3,
    baseProduction: 5,
    img: {
      src: "./static/img/ouh.png",
    },
    name: "",
    neededProduction: 10,
  },
  {
    id: buildingType.richard,
    amountMultiplier: 1.1,
    baseAmount: 1e4,
    baseProduction: 25,
    description: "Le justicier masqué",
    name: "Richard sans peur",
    neededProduction: 50,
  },
  {
    id: buildingType.lorenzo,
    amountMultiplier: 1.1,
    baseAmount: 1e5,
    baseProduction: 1e2,
    name: "Lorenzo Lovegun",
    neededProduction: 300,
  },
  {
    id: buildingType.thamos,
    amountMultiplier: 1.1,
    baseAmount: 1.2e6,
    baseProduction: 1e3,
    name: "Thamos, destructeur des mondes",
    neededProduction: 1e3,
  },
  {
    id: buildingType.patoche,
    amountMultiplier: 1.1,
    baseAmount: 6e6,
    baseProduction: 2e3,
    description: "Faîtes moi confiances les potos.",
    name: "Patoche Balkanoche",
    neededProduction: 6e3,
  },
  {
    id: buildingType.sardoche,
    amountMultiplier: 1.1,
    baseAmount: 1.6e7,
    baseProduction: 3.5e3,
    description: "C'était sûr qu'il allait venir.",
    name: "Sardoche",
    neededProduction: 2.5e4,
  },
  {
    id: buildingType.jeanMichel,
    amountMultiplier: 1.1,
    baseAmount: 2.4e8,
    baseProduction: 1e4,
    description: "Quelqu'un a le code de la wifi ?",
    name: "Jean-Michel Cinquejet",
    neededProduction: 7.5e4,
  },
  {
    id: buildingType.leeroy,
    amountMultiplier: 1.1,
    baseAmount: 4e9,
    baseProduction: 1e5,
    description: "Vous voulez du poulet ?",
    name: "Leeroy Jenkins",
    neededProduction: 1.5e5,
  },
  {
    id: buildingType.canardMan,
    amountMultiplier: 1.1,
    baseAmount: 4e10,
    baseProduction: 5e5,
    description: "Les bugs n'ont qu'à bien se tenir.",
    name: "Canard man",
    neededProduction: 2e6,
  },
  {
    id: buildingType.jeanne,
    amountMultiplier: 1.1,
    baseAmount: 2.8e11,
    baseProduction: 1.5e6,
    description: "On m'a appelée ?",
    name: "Jeanne d'Haussecourt",
    neededProduction: 1e7,
  },
  {
    id: buildingType.katlyn,
    amountMultiplier: 1.1,
    baseAmount: 7e11,
    baseProduction: 3.5e6,
    description: "L'enfant sauvage dôté de pouvoir mystique",
    name: "Katlyn, fille de Mowkaz",
    neededProduction: 3e7,
  },
  {
    id: buildingType.christ,
    amountMultiplier: 1.09,
    baseAmount: 5e12,
    baseProduction: 9e6,
    name: "Le Christ Cosmique",
    neededProduction: 5e7,
  },
  {
    id: buildingType.miyagi,
    amountMultiplier: 1.09,
    baseAmount: 2e13,
    baseProduction: 2.25e7,
    name: "Maître Miyagi",
    neededProduction: 1e8,
  },
  {
    id: buildingType.bebou,
    amountMultiplier: 1.08,
    baseAmount: 3e14,
    baseProduction: 1e8,
    name: "Beboux, Émissaire du Cringe",
    neededProduction: 1e9,
  },
  {
    id: buildingType.bruce,
    amountMultiplier: 1.07,
    baseAmount: 4e15,
    baseProduction: 5e8,
    name: "Bruce Lomsaley",
    neededProduction: 1e10,
  },
  {
    id: buildingType.petyr,
    amountMultiplier: 1.05,
    baseAmount: 5e16,
    baseProduction: 5e9,
    name: "Petyr et Styven",
    neededProduction: 2e11,
  },
  {
    id: buildingType.heenok,
    amountMultiplier: 1.04,
    baseAmount: 1e18,
    baseProduction: 1.5e11,
    description:
      "Inclinez-vous devant le Roi, quitte à avoir mal aux chevilles.",
    name: "Heenok",
    neededProduction: 1e15,
  },
  {
    id: buildingType.mother,
    amountMultiplier: 1.03,
    baseAmount: 1.5e19,
    baseProduction: 3e12,
    name: "Mère",
    neededProduction: 2e16,
  },
];
export default {
  buildingList,
};
