
export const buildingList: IBuilding[] = [
  {
    id: buildingType.chercheur,
    amountMultiplier: 1.03,
    baseAmount: 25,
    baseProduction: 0.2,
    img: {
      src: "./static/img/building/scientist.jpg",
    },
    name: "Chercheur",
    neededProduction: 0,
  },
  {
    id: buildingType.raoult,
    amountMultiplier: 1.03,
    baseAmount: 1.25e2,
    baseProduction: 1,
    img: {
      src: "./static/img/building/raoult.jpg",
    },
    name: "Raoul la fripouille",
    neededProduction: 1,
  },
  {
    id: buildingType.monkey,
    amountMultiplier: 1.03,
    baseAmount: 7.5e2,
    baseProduction: 5,
    img: {
      src: "./static/img/ouh.png",
    },
    name: "",
    neededProduction: 10,
  },
  {
    id: buildingType.richard,
    amountMultiplier: 1.03,
    baseAmount: 5e3,
    baseProduction: 25,
    description: "Le justicier masqué",
    img: {
      src: "./static/img/building/richard.jpg",
    },
    name: "Richard sans peur",
    neededProduction: 50,
  },
  {
    id: buildingType.lorenzo,
    amountMultiplier: 1.03,
    baseAmount: 2.5e4,
    baseProduction: 1e2,
    img: {
      src: "./static/img/building/lorenzo.jpg",
    },
    name: "Lorenzo Lovegun",
    neededProduction: 300,
  },
  {
    id: buildingType.thamos,
    amountMultiplier: 1.05,
    baseAmount: 1e5,
    baseProduction: 3e2,
    img: {
      src: "./static/img/building/thamos.jpg",
    },
    name: "Thamos, destructeur des mondes",
    neededProduction: 1e3,
  },
  {
    id: buildingType.patoche,
    amountMultiplier: 1.05,
    baseAmount: 5e5,
    baseProduction: 1e3,
    description: "Faîtes moi confiances les potos.",
    img: {
      src: "./static/img/building/patoche.jpg",
    },
    name: "Patoche Balkanoche",
    neededProduction: 6e3,
  },
  {
    id: buildingType.sardox,
    amountMultiplier: 1.05,
    baseAmount: 2e6,
    baseProduction: 3.5e3,
    description: "C'était sûr qu'il allait venir.",
    img: {
      src: "./static/img/building/sardox.jpg",
    },
    name: "Sardox",
    neededProduction: 2.5e4,
  },
  {
    id: buildingType.jeanMichel,
    amountMultiplier: 1.05,
    baseAmount: 1e7,
    baseProduction: 1.5e4,
    description: "Quelqu'un a le code de la wifi ?",
    img: {
      src: "./static/img/building/jean-michel.jpg",
    },
    name: "Jean-Michel Cinquejet",
    neededProduction: 7.5e4,
  },
  {
    id: buildingType.leeroy,
    amountMultiplier: 1.05,
    baseAmount: 9e7,
    baseProduction: 1e5,
    description: "Vous voulez du poulet ?",
    img: {
      src: "./static/img/building/leeroy.jpg",
    },
    name: "Leeroy Jenkins",
    neededProduction: 1.5e5,
  },
  {
    id: buildingType.canardMan,
    amountMultiplier: 1.07,
    baseAmount: 5e8,
    baseProduction: 5e5,
    description: "Les bugs n'ont qu'à bien se tenir.",
    name: "Canard man",
    neededProduction: 2e6,
  },
  {
    id: buildingType.jeanne,
    amountMultiplier: 1.07,
    baseAmount: 1.15e9,
    baseProduction: 1e6,
    description: "On m'a appelée ?",
    name: "Jeanne d'Haussecourt",
    neededProduction: 1e7,
  },
  {
    id: buildingType.katlyn,
    amountMultiplier: 1.07,
    baseAmount: 6.66666666e9,
    baseProduction: 4e6,
    description: "L'enfant sauvage dôté de pouvoir mystique",
    name: "Katlyn, fille de Mowkaz",
    neededProduction: 3e7,
  },
  {
    id: buildingType.christ,
    amountMultiplier: 1.07,
    baseAmount: 3e11,
    baseProduction: 1.5e8,
    name: "Le Christ Cosmique",
    neededProduction: 1.5e8,
  },
  {
    id: buildingType.miyagi,
    amountMultiplier: 1.07,
    baseAmount: 1e12,
    baseProduction: 4.25e8,
    name: "Maître Miyagi",
    neededProduction: 1e9,
  },
  {
    id: buildingType.bebou,
    amountMultiplier: 1.1,
    baseAmount: 2e13,
    baseProduction: 7.5e9,
    name: "Beboux, Émissaire du Cringe",
    neededProduction: 1e10,
  },
  {
    id: buildingType.bruce,
    amountMultiplier: 1.1,
    baseAmount: 2e14,
    baseProduction: 6.3e10,
    name: "Bruce Lomsaley",
    neededProduction: 1e11,
  },
  {
    id: buildingType.petyr,
    amountMultiplier: 1.1,
    baseAmount: 9e15,
    baseProduction: 2.3e12,
    name: "Petyr et Styven",
    neededProduction: 2e12,
  },
  {
    id: buildingType.heenok,
    amountMultiplier: 1.1,
    baseAmount: 1.5e17,
    baseProduction: 3.1e13,
    description:
      "Inclinez-vous devant le Roi, quitte à avoir mal aux chevilles.",
    name: "Heenok",
    neededProduction: 1e14,
  },
  {
    id: buildingType.mother,
    amountMultiplier: 1.1,
    baseAmount: 9.99999999999e19,
    baseProduction: 9.999999e15,
    name: "Mère",
    neededProduction: 2e16,
  },
];
export default {
  buildingList,
};